#include<linux/module.h>
#include<linux/init.h>
#include<linux/fs.h>
#include<linux/slab.h>
#include<linux/stat.h>
#include<linux/kernel.h>
#include<linux/cdev.h>
#include<linux/moduleparam.h>
MODULE_LICENSE("GPL");
