#! /bin/bash

for file in $(ls *.h) $(ls *.c)
	do
	ci $file
	done

for file in $(ls *.h,v) $(ls *.c,v)
	do
	co $file
	done
Runapp()
{
	unlink Mydev
	read -n1 -p "Do you want to compile Application?(y/n)"
	if [ $REPLY = 'y' ]
	then
		if (make -C ./Application)
		then
	read -n1 -p "Do you want to run Application?(y/n)"
	if [ $REPLY = 'y' ]
	then
		
	echo -n1 -p "Enter the Major no:" 
		read majorno 
		mknod Mydev c $majorno 0
		cd /home/anmolzehra/Projects/drivers/Testdriver/Application
		make
		./app
		cd ..
		
	fi
	fi
	fi
	Removedriver
}
Builddriver()
{
	if ( make )
		then
			Insertdriver
	else
		echo"make failed"
			read
			fi
}
Insertdriver()
{
	read -n1 -p "Do you want to insert driver? (y/n)"
		if [ $REPLY = 'y' ]
			then
				if (insmod ./modules/lkm107.ko nod=10) 
					then
						lsmod
						read
						dmesg
						read
						cat /proc/devices
						read
						cat /proc/modules
						read
						Runapp
						fi
				else
					echo"Never Mind"
						fi
}
Removedriver()
{
	read -n1 -p "Do you want to remove driver ?(y/n)"
		if [ $REPLY = 'y' ]
			then
				if (rmmod lkm107)
					then
						lsmod
						read
						dmesg
						read
						cat /proc/devices
						read
						cat /proc/modules
						read
						fi
				else
					echo"Happy working with device"
						fi
}

Builddriver
read -n1 -p "Do you want to edit further ?(y/n)" resp
if [ $resp = 'y' ]
	then
for file in $(ls *.h,v)
	do
	co -l $file
	done

for file in $(ls *.c,v)
	do
	co -l $file
	done

	fi

